/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    // This allows you to use 'BootJar' type in your convention plugins
    implementation(libs.spring.boot.gradle.plugin)

    // Also add Kotlin if you use Kotlin-specific tasks in your conventions
    implementation(libs.kotlin.gradle.plugin)
    implementation(libs.kotlin.allopen)
    implementation(libs.spring.dependency.management.plugin)
    implementation(libs.graalvm.gradle.plugin)
}
